# -*- coding: utf-8 -*-
{
    "name": "Theme Lyon",
    "summary": "Backend theme, Enterprise, responsive theme",
    "version": "15.0.1",
    "category": "Theme/Backend",
    "license": "OPL-1",
    "support": "relief.4technologies@gmail.com",  
    "author" : "Relief Technologies",    
    "installable": True,
    "depends": ["web", "mail"],   
    "data": ["views/res_users.xml", "views/web.xml"],
    "assets": {
        "web.assets_frontend": [
            "/lyon_backend_theme/static/src/legacy/js/website_apps_menu.js",
            "/lyon_backend_theme/static/src/legacy/scss/website_apps_menu.scss",
            "/lyon_backend_theme/static/src/scss/login.scss",
        ],
        "web.assets_backend": [
            "/lyon_backend_theme/static/src/legacy/scss/lyon_backend_theme.scss",
            "/lyon_backend_theme/static/src/legacy/js/lyon_backend_theme.js",
            "/lyon_backend_theme/static/src/legacy/scss/kanban_view_mobile.scss",
            "/lyon_backend_theme/static/src/legacy/js/kanban_renderer_mobile.js",
            "/lyon_backend_theme/static/src/components/ui_context.esm.js",
            "/lyon_backend_theme/static/src/components/apps_menu/apps_menu.scss",
            "/lyon_backend_theme/static/src/components/apps_menu/apps_menu.esm.js",
            "/lyon_backend_theme/static/src/components/navbar/main_navbar.scss",
            "/lyon_backend_theme/static/src/components/control_panel/control_panel.scss",
            "/lyon_backend_theme/static/src/components/control_panel/control_panel.esm.js",
            "/lyon_backend_theme/static/src/components/search_panel/search_panel.scss",
            "/lyon_backend_theme/static/src/components/search_panel/search_panel.esm.js",
            "/lyon_backend_theme/static/src/components/attachment_viewer/attachment_viewer.scss",
            "/lyon_backend_theme/static/src/components/attachment_viewer/attachment_viewer.esm.js",
            "/lyon_backend_theme/static/src/components/hotkey/hotkey.scss",
            "/lyon_backend_theme/static/src/scss/theme.scss",
            "/lyon_backend_theme/static/src/scss/dark_mode.scss",
            "/lyon_backend_theme/static/src/js/systray/systray_dark_mode_menu.js",
        ],
        "web.assets_qweb": [
            "/lyon_backend_theme/static/src/xml/dark_mode.xml",
            "/lyon_backend_theme/static/src/legacy/xml/form_buttons.xml",
            "/lyon_backend_theme/static/src/components/apps_menu/apps_menu.xml",
            "/lyon_backend_theme/static/src/components/control_panel/control_panel.xml",
            "/lyon_backend_theme/static/src/components/navbar/main_navbar.xml",
            "/lyon_backend_theme/static/src/components/search_panel/search_panel.xml",
            "/lyon_backend_theme/static/src/components/attachment_viewer/attachment_viewer.xml",
            "/lyon_backend_theme/static/src/components/hotkey/hotkey.xml",    
            "/lyon_backend_theme/static/src/xml/systray_dark_mode_menu.xml",        
        ],
        
    },
    'images': [
        'static/description/banner.png',
        'static/description/theme_screenshot.gif',
    ],
    "sequence": 1,
    "auto_install": False,
    "price": 45,
    "currency": "EUR"
}
